baseURL = "https://ar.al/"
languageCode = "en-us"
title = "Aral Balkan"
publishDir = "./dist/site"
PygmentsCodeFences = true
PygmentsStyle = "friendly"
enableGitInfo = true

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License"
"rssLimit" = 20

[author]
  name = "Aral Balkan"
  email = "mail@ar.al"
