#!/bin/bash

################################################################################
#
# ar.al single-shot deployment script.
#
# Uses Hugo (gohugo.io) and Site.js (https://sitejs.org).
#
################################################################################

# Remove any previously-generated content (Hugo does not remove content)
rm -rf dist/site

# Build the site
# (The destination is a subdirectory of the dist folder because we also have
# a site archive that we want to deploy and the easie)
hugo --baseURL=https://ar.al

# Deploy it
site dist --sync-to=ar.al --exit-on-sync
