#!/bin/bash

# Runs command in requested directory in the background
# and restores the working directory at the end.
# Usage: runInBackground <directory> "<command>"
runInBackground(){
	pushd $1 >/dev/null
	eval $2 &
	popd >/dev/null
}

# With thanks to Job Vranish for his awesome tutorial
# on starting/stopping background processes in Bash:
# https://spin.atomicobject.com/2017/08/24/start-stop-bash-background-process/
trap "exit" INT TERM ERR
trap "kill 0" EXIT

# Start the rsync deployment watcher
runInBackground ../sync "npm run sync"

# Start Hugo server.
#
# The baseURL and appendPort flags are set to overwrite the default behaviour
# of Hugo when run with the server option which is to write absolute URLs
# as localhost:<port> regardless of the setting of baseURL in the config.toml
# file. Since we do not have a separate build/deploy phase to the live server,
# we want the site as it would exist on the server to exist on the client.
#
# Note: if you do not want a post live-synced, mark it as draft: true in the
# ===== front matter.
#
hugo server --renderToDisk --baseURL=https://ar.al --appendPort=false

# Don’t exit. Shutting off this process should also kill
# the two other background processes we started
wait
